/*******************************************************************************
 *  avast! Online Security plugin - Mustache.js HTML Templates - cross browser
 *  (c) 2014 Avast Corp.
 ******************************************************************************/

var AvastWRC = AvastWRC || {};


AvastWRC.Templates = {
  /**
   * Process templates declaration and append templates to container
   */
  add: function (declaration) {
    function addPart(acc, part) {
      if (part instanceof Array) {
        for (var i = 0; i < part.length; i++) {
          addPart(acc, part[i]);
        }
      } else if (part instanceof Object) {
        // reference within declaration
        if (part.temp) {
          var temp = declaration[part.temp] || AvastWRC.Templates[part.temp];
          addPart(acc, (part.sect !== undefined) ? temp[part.sect] : temp);
        }
      } else {
        acc.push(part);
      }
    }

    for (var temp in declaration) {
      var parts = [];
      addPart(parts, declaration[temp]);
      this[temp] = parts.join('\n');
    }
  }
};

/*------------------------ SafeShop bar UI templates -------------------------*/
AvastWRC.Templates.add(
  { // --- Templates Declaration
      safePriceRootTemplate: [
          '<span class="notranslate" style="display: none" id="a-sp-root-template"></span>'
      ],

      safeShopPanel:[
      '<div class="a-sp-panel" id="a-panel">',
        '<div class="a-sp-panel-header" id="a-panel-header">',
          '<img ondragstart="return false;" class="a-sp-header-top-left" src="{{panelData.images.logo}}" onerror="this.src=\'{{panelData.images.logo}}\';"/>',
          '<div class="a-sp-header-top-right">',
            '<div class="sp-header-top-close" id="closePanel" style="background-image: url({{panelData.images.close}});" title="{{panelData.strings.spCloseTooltip}}"></div>',
            '<div class="sp-header-top-min"  id="minPanel" style="background-image: url({{panelData.images.min}});" title="{{panelData.strings.spMinimizeTooltip}}"></div>',
            '<div class="sp-header-top-help"  id="helpPanel" style="background-image: url({{panelData.images.help}});" title="{{panelData.strings.spHelpTooltip}}"></div>',
            '<div class="sp-header-top-settings"  id="settingsPanel" style="background-image: url({{panelData.images.settings}});" title="{{panelData.strings.spSettingsTooltip}}"></div>',
          '</div>',
          '<div class="a-sp-header-bottom-col1" id="offersTab">{{panelData.strings.spOffersTab}}<span id="offersTabState" class="{{^offersToBeShown}}a-sp-shown{{/offersToBeShown}}{{#offersToBeShown}}a-sp-to-be-shown{{/offersToBeShown}}"/>',
          '</div>',
          '<div class="a-sp-header-bottom-separator-1-2">',
          '</div>',
          '<div class="a-sp-header-bottom-col2-selected" id="couponsTab">{{panelData.strings.spCouponsTab}}<span id="couponsTabState" class="{{^couponsToBeShown}}a-sp-shown{{/couponsToBeShown}}{{#couponsToBeShown}}a-sp-to-be-shown{{/couponsToBeShown}}"/>',
          '</div>',
          '<div class="a-sp-header-bottom-separator-2-3">',
          '</div>',
          '<div class="a-sp-header-bottom-col3" id="othersTab">{{panelData.strings.spOthersTab}}<span id="othersTabState" class="{{^othersToBeShown}}a-sp-shown{{/othersToBeShown}}{{#othersToBeShown}}a-sp-to-be-shown{{/othersToBeShown}}"/>',
          '</div>',
        '</div>',
        '<div class="a-sp-items-wrapper">',
          {temp: 'offersItemsWrapper'},
          {temp: 'couponsItemsWrapper'},
          {temp: 'othersItemsWrapper'},
        '</div>',
        {temp: 'panelSecurity'},
        {temp: 'ratePanel'},
        {temp: 'resizeBar'},

        // '<div class="asp-items-scrollbar-wrapper">',
        //   '<div class="asp-items-scrollbar"></div>',
        // '</div>',
      '</div>',
    ],

    settingsTooltip: [
      '{{#panelData.showSettingsTooltip}}',
        '<div class="asp-settings-tooltip">',
          '<div class="asp-default-tooltip-text">{{panelData.strings.spOnboardingSettingsMsg}}</div>',
          '<div class="asp-default-tooltip-button" id="settingsTooltipButton">{{panelData.strings.spOnboardingSettingsButton}}</div>',
        '</div>',
      '{{/panelData.showSettingsTooltip}}',
    ],
    offersItemsWrapper: [
      '<div class="a-sp-offers-items-wrapper" id="offersItemsWrapper">',
        '{{#panelData.searchConfig.offers.active}}{{^hotelsCity.length}}',
          '<div id="searchOffersWrapper{{#accommodationsLength}}{{^panelData.strings.searchTitleOffers}} asp-sas-display-none{{/panelData.strings.searchTitleOffers}}{{/accommodationsLength}}">',
            {temp: 'searchOffersBox'},
          '</div>',
        '{{/hotelsCity.length}}{{/panelData.searchConfig.offers.active}}',
        '<div id="offersWrapper">',
          '{{#offerstTotalLength}}',
            {temp: 'offersWrapper'},
          '{{/offerstTotalLength}}',
          '{{^offerstTotalLength}}',
            '{{#panelData.searchConfig.offers.active}}',
              '{{#isOffersSearch}}',
                {temp: 'nothingFoundOffers'},
              '{{/isOffersSearch}}',
              '{{^isOffersSearch}}',
                {temp: 'searchForOffers'},
              '{{/isOffersSearch}}',
            '{{/panelData.searchConfig.offers.active}}',
            '{{^panelData.searchConfig.offers.active}}',
              {temp: 'nothingFoundOffers'},
            '{{/panelData.searchConfig.offers.active}}',
          '{{/offerstTotalLength}}',
        '</div>',
      '</div>',
    ],

    couponsItemsWrapper: [
      '<div class="a-sp-coupons-items-wrapper" id="couponsItemsWrapper">',
        '{{#panelData.searchConfig.coupons.active}}',
          '<div id="searchCouponsWrapper">',
            {temp: 'searchCouponsBox'},
          '</div>',
        '{{/panelData.searchConfig.coupons.active}}',
        '<div id="couponsWrapper">',
          '{{#coupons.length}}',
              {temp: 'couponsWrapper'},
          '{{/coupons.length}}',
          '{{^coupons.length}}',
              '{{#panelData.searchConfig.coupons.active}}',
              '{{#isCouponsSearch}}',
                  {temp: 'nothingFoundCoupons'},
              '{{/isCouponsSearch}}',
              '{{^isCouponsSearch}}',
                  {temp: 'searchForCoupons'},
              '{{/isCouponsSearch}}',
              '{{/panelData.searchConfig.coupons.active}}',
              '{{^panelData.searchConfig.coupons.active}}',
              {temp: 'nothingFoundCoupons'},
              '{{/panelData.searchConfig.coupons.active}}',
          '{{/coupons.length}}',
        '</div>',
      '</div>',
    ],

    othersItemsWrapper: [
      '<div class="a-sp-others-items-wrapper" id="othersItemsWrapper">',
        '<div id="othersWrapper">',
          '{{#redirectLength}}',
            {temp: 'othersWrapper'},
          '{{/redirectLength}}',
          '{{^redirectLength}}',
            {temp: 'nothingFoundOthers'},
          '{{/redirectLength}}',
        '</div>',
      '</div>',
    ],

    safeShopCouponPanel:[
      '<div class="a-sp-coupon-panel" id="a-coupon-panel">',
        '<div class="a-sp-container-top">',
          '<div class="a-sp-panel-header" id="couponPanelHeader">',
            '<img ondragstart="return false;" class="a-sp-panel-header-icon" src="{{appiedCouponData.images.logo}}" onerror="this.src=\'{{appiedCouponData.images.logo}}\';"/>',
            '<div class="a-sp-panel-header-close" id="closeCouponPanel" style="background-image: url({{appiedCouponData.images.close}});"></div>',
          '</div>',
          '{{^code}}',
            '<div class="a-sp-applied-info">',
              '<img ondragstart="return false;" class="a-sp-panel-applied-icon" src="{{appiedCouponData.images.checkMarkIcon}}" onerror="this.src=\'{{appiedCouponData.images.checkMarkIcon}}\';"/>',
              '<div class="a-sp-panel-applied-text">{{appiedCouponData.strings.sasCouponAppliedOnPage}}</div>',
            '</div>',
          '{{/code}}',
          '{{#code}}',
            '<div class="asp-coupon-with-code" cupcod="{{code}}">',
              '<div class="asp-coupon-item-copy-code">{{{appiedCouponData.strings.spClickThenPaste}}}</div>',
              '<div class="asp-coupon-item-coupon-code"  cupcod="{{code}}">',
                '<div class="asp-coupon-item-coupon-code-text asp-code-opacity" cupcod="{{code}}">{{code}}</div>',
                '<div class="asp-coupon-item-coupon-code-text-copied">{{appiedCouponData.strings.spCodeCopied}}</div>',
              '</div>',
            '</div>',
          '{{/code}}',
        '</div>',
        {temp: 'dashedLineSeparator'},
        '{{#coupons}}{{#selected}}',
            {temp: 'couponTop'},
            '{{^appiedCouponData.browserType.isFirefox}}',
              '{{^rated}}',
                {temp: "rateAppliedCoupons"},
              '{{/rated}}',
            '{{/appiedCouponData.browserType.isFirefox}}',
        '{{/selected}}{{/coupons}}',
      '</div>',
    ],

    safeShopMinimizedPanel: [
        '<div id="asp-panel-min" class="asp-panel-minimized-wrapper a-sp-notifications-hidden">',
            '<div id="asp-panel-minimized-top-circle" class="asp-panel-minimized-inner">',
              '<img class="asp-panel-minimized-logo" ondragstart="return false;" src="{{panelData.images.logo}}" onerror="this.src=\'{{panelData.images.logo}}\';"/>',
            '</div>',
            '<div id="asp-panel-min-circle" class="asp-panel-minimized">',
                '<div id="asp-panel-min-badge" class="asp-panel-badge">',
                  '<div class="asp-panel-badge-text">',
                    '{{#detailsToClosed}}',
                      '{{#detailsToClosed.offerNumber}}',
                        '{{detailsToClosed.offerNumber}}',
                      '{{/detailsToClosed.offerNumber}}',
                      '{{^detailsToClosed.offerNumber}}0{{/detailsToClosed.offerNumber}}',
                    '{{/detailsToClosed}}</div>',
                    '{{^detailsToClosed}}0{{/detailsToClosed}}',
                    '</div>',
                '</div>',
            '</div>',
            '<div id="asp-panel-minimized-inner-circle" class="asp-panel-minimized-inner-circle"></div>',
        '</div>'
    ],
    searchForOffers:[
      '<div class="asp-search-for">',
        '<img class="asp-search-for-icon" ondragstart="return false;" src="{{panelData.images.searchOffers}}" onerror="this.src=\'{{panelData.images.searchOffers}}\';"/>',
        '<div class="asp-search-for-text">{{{panelData.strings.spSearchForOffers}}}</div>',
      '</div>',
    ],
    nothingFoundOffers:[
        '<div class="asp-nothing-found{{^panelData.searchConfig.offers.active}}-60{{/panelData.searchConfig.offers.active}}">',
          '<img class="asp-nothing-found-icon" ondragstart="return false;" src="{{panelData.images.noOffers}}" onerror="this.src=\'{{panelData.images.noOffers}}\';"/>',
          '<div class="asp-nothing-found-text">{{{panelData.strings.spNoResultsFoundOffers}}}</div>',
          '{{#panelData.emptySearchConfig.offers.url}}',
            '<div class="asp-nothing-found-try-in">{{panelData.emptySearchConfig.offers.trySearchIn}}</div>',
            '<div class="asp-nothing-found-go-in-button" id="asp-nothing-found-go-in-button-offers" resurl="{{panelData.emptySearchConfig.offers.url}}">{{panelData.emptySearchConfig.offers.searchIn}}</div>',
            '<img class="asp-nothing-found-go-in-image" ondragstart="return false;" src="{{panelData.emptySearchConfig.offers.image}}" onerror="this.src=\'{{panelData.emptySearchConfig.offers.image}}\';"/>',
          '{{/panelData.emptySearchConfig.offers.url}}',
        '</div>',
    ],
    searchForCoupons:[
      '<div class="asp-search-for">',
        '<img class="asp-search-for-icon" ondragstart="return false;" src="{{panelData.images.searchCoupons}}" onerror="this.src=\'{{panelData.images.searchCoupons}}\';"/>',
        '<div class="asp-search-for-text">{{{panelData.strings.spSearchForCoupons}}}</div>',
      '</div>',
    ],
    nothingFoundCoupons:[
        '<div class="asp-nothing-found{{^panelData.searchConfig.coupons.active}}-60{{/panelData.searchConfig.coupons.active}}">',
          '<img class="asp-nothing-found-icon" ondragstart="return false;" src="{{panelData.images.noCouponsImg}}" onerror="this.src=\'{{panelData.images.noCouponsImg}}\';"/>',
          '<div class="asp-nothing-found-text">{{{panelData.strings.spNoResultsFoundCouponsNow}}}</div>',
          '{{#panelData.emptySearchConfig.coupons.url}}',
            '<div class="asp-nothing-found-try-in">{{panelData.emptySearchConfig.coupons.trySearchIn}}</div>',
            '<div class="asp-nothing-found-go-in-button" id="asp-nothing-found-go-in-button-coupons" resurl="{{panelData.emptySearchConfig.coupons.url}}">{{panelData.emptySearchConfig.coupons.searchIn}}</div>',
            '<img class="asp-nothing-found-go-in-image" ondragstart="return false;" src="{{panelData.emptySearchConfig.coupons.image}}" onerror="this.src=\'{{panelData.emptySearchConfig.coupons.image}}\';"/>',
          '{{/panelData.emptySearchConfig.coupons.url}}',
        '</div>',
    ],
    nothingFoundOthers:[
        '<div class="asp-nothing-found-60">',
          '<img class="asp-nothing-found-icon" ondragstart="return false;" src="{{panelData.images.noOffers}}" onerror="this.src=\'{{panelData.images.noOffers}}\';"/>',
          '<div class="asp-nothing-found-text">{{{panelData.strings.spNoresultsFoundForOthers}}}</div>',
        '</div>',
    ],
    // SafeShop Products dropdown
    offersWrapper:[
      '<div id="offersWrapper">',
        '{{#hotelsPriceComp.length}}',
          '<div class="asp-separator-text-first">{{panelData.strings.spAvailableHotels}}</div>',
          '{{#hotelsPriceComp}}',
            {temp: 'hotelItem'},
          '{{/hotelsPriceComp}}',
        '{{/hotelsPriceComp.length}}',
        '{{#hotelsCity.length}}',
          '<div class="asp-separator-text-first">{{panelData.strings.spCityHotelNotificationMessage}} <b>{{cityName}}</b></div>',
          '{{#hotelsCity}}',
            {temp: 'hotelItem'},
          '{{/hotelsCity}}',
        '{{/hotelsCity.length}}',
        '{{#hotelsSimilar.length}}',
        '<div class="asp-separator-text-first">{{panelData.strings.spSimilarHotelsMessage}}</div>',
          '{{#hotelsSimilar}}',
            {temp: 'hotelItem'},
          '{{/hotelsSimilar}}',
        '{{/hotelsSimilar.length}}',
        '{{#products.length}}',
          '<div class="asp-separator-text-first">{{panelData.strings.spAvailableOffers}}</div>',
          '{{#products}}',
            {temp: 'offerItem'},
          '{{/products}}',
        '{{/products.length}}',
        '{{#social.showInBottomOffers}}',
            {temp: 'socialSharing'},
        '{{/social.showInBottomOffers}}',
      '</div>',
    ],

    hotelItem:[
      '<div class="asp-offer-item" resurl="{{url}}" isSearch="{{isSearch}}">',
        '<div class="asp-offer-top-row">',
          '<div class="asp-offer-left-hotel">',
            '<img ondragstart="return false;" class="asp-offer-item-image" src="{{affiliateImage}}" onerror="this.src=\'{{panelData.images.placeholder}}\';"/>',
          '</div>',
          '<div class="asp-offer-right">',
            '<div class="asp-offer-first-row">',
              '<div class="asp-offer-item-title">{{title}}</div>',
            '</div>',
            '<div class="asp-offer-second-row">',
              '{{#starsToShow}}',
                {temp: 'starsRating'},
              '{{/starsToShow}}',
              '{{#affiliate}}<div class="asp-offer-affiliate-name">{{affiliate}}</div>{{/affiliate}}',
            '</div>',
            '{{#additionalFees}}',
              '<div class="asp-offer-third-row">',
                '<div class="asp-offer-item-hotel-fee">{{panelData.strings.spAdditionalFees}}</div>',
              '</div>',
            '{{/additionalFees}}',
            '{{#showPrice}}',
              {temp: 'offerBottomRow'},
            '{{/showPrice}}',
        '</div>',
        '</div>',
      '</div>'
    ],

    // SafeShop Products list item
    offerItem:[
      '<div class="asp-offer-item" resurl="{{url}}" isSearch="{{isSearch}}">',
        '<div class="asp-offer-top-row">',
          '<div class="asp-offer-left">',
              '<img ondragstart="return false;" class="asp-offer-item-image" src={{#productImage}}"{{productImage}}"{{/productImage}}{{^productImage}}"{{image}}"{{/productImage}} onerror="this.src=\'{{panelData.images.searchOffers}}\';"/>',
          '</div>',
          '<div class="asp-offer-right">',
            '<div class="asp-offer-first-row">',
              '<div class="asp-offer-item-title">{{title}}</div>',
            '</div>',
            '<div class="asp-offer-second-row">',
              '{{#affiliate}}<div class="asp-offer-affiliate-name">{{affiliate}}</div>{{/affiliate}}',
            '</div>',
            '<div class="asp-offer-third-row">',
              '{{#shipping}}',
                '<div class="asp-offer-item-shipping">{{panelData.strings.spShippingLabel}} {{shipping}}</div>',
              '{{/shipping}}',
            '</div>',
            '{{#showPrice}}',
              {temp: 'offerBottomRow'},
            '{{/showPrice}}',
          '</div>',
        '</div>',
      '</div>'
    ],
    offerBottomRow: [
      '<div class="asp-offer-bottom-row">',
        '{{#saving}}',
          '<div class="asp-offer-item-price-stroke-row">',
              '<div class="asp-offer-item-price-stroke above">{{queryFormatedPrice}}</div>',
          '</div>',
          '<div class="asp-offer-item-discount-banner-offers" style="background-image: url({{panelData.images.ribbonOffers}});">',
            '<div class="asp-offer-item-discount-banner-offers-text">- {{saving}}</div>',
          '</div>',
        '{{/saving}}',
        '{{^saving}}',
          '<div class="asp-offer-item-price-stroke-row-empty"></div>',
        '{{/saving}}',
        '{{#showPrice}}',
          '<div class="asp-offer-item-price">{{formattedPrice}}</div>',
        '{{/showPrice}}',
      '</div>'
    ],
    //coupons
    lessDesc: [
      '<span class="asp-coupon-description-less">{{panelData.strings.spNotificationRedirectShowLessMessage}}</span>',
    ],
    moreDesc: [
      '<span class="asp-coupon-description-more">{{panelData.strings.spNotificationRedirectShowMoreMessage}}</span>',
    ],
    couponDescText: [
      '<div id="couponsCompleteDesc" class="asp-coupon-description-text {{#couponTextIsLong}}asp-description-hidden{{/couponTextIsLong}}">{{text}}',
       '{{#couponTextIsLong}}',
          {temp: "lessDesc"},
       '{{/couponTextIsLong}}',
      '</div>',
      '{{#couponTextIsLong}}',
        '<div id="couponsOneLineDesc" class="asp-coupon-description-text asp-more-info-to-show">{{couponTextIsLong}}',
        {temp: "moreDesc"},
      '</div>',
      '{{/couponTextIsLong}}',
    ],
    separatorTextFirst: [
      '<div id="asp-separator-text-first" class="asp-separator-text-first {{#selectedCouponAnimation}}asp-separator-text-hidden{{/selectedCouponAnimation}}">{{panelData.strings.spSelectedCoupons}}</div>',
    ],
    rateAppliedCoupons: [
      '<div class="asp-coupon-rate-container">',
        '<div class="asp-coupon-rate-container-shape">',
          '{{#code}}',
            '<div class="asp-coupon-rate-text{{#spCouponWorksIsLong}}-long{{/spCouponWorksIsLong}}">',
              '{{^appiedCouponData}}{{panelData.strings.spCouponCodeWorks}}{{/appiedCouponData}}',
              '{{#appiedCouponData}}{{appiedCouponData.strings.spCouponCodeWorks}}{{/appiedCouponData}}',
            '</div>',
          '{{/code}}',
          '{{^code}}',
            '<div class="asp-coupon-rate-text{{#spCouponCodeWorksIsLong}}-long{{/spCouponCodeWorksIsLong}}">',
              '{{^appiedCouponData}}{{panelData.strings.spCouponWorks}}{{/appiedCouponData}}',
              '{{#appiedCouponData}}{{appiedCouponData.strings.spCouponWorks}}{{/appiedCouponData}}',
            '</div>',
          '{{/code}}',
          '{{#appiedCouponData}}',
          '<div class="asp-coupon-rate-thanks" resurl="{{couponUrl}}">{{appiedCouponData.strings.spRateCouponsThanks}}</div>',
            '<img ondragstart="return false;" class="asp-coupon-rate-positive"  resurl="{{couponUrl}}" isSearch="{{isSearch}}" isContextCoupon="{{isContextCoupon}}"',
              'src="{{appiedCouponData.images.rateCouponPositive}}"',
              'onmouseover="this.src=\'{{appiedCouponData.images.rateCouponPositiveHover}}\'"',
              'onmouseout="this.src=\'{{appiedCouponData.images.rateCouponPositive}}\'"/>',
            '<img ondragstart="return false;" class="asp-coupon-rate-negative"  resurl="{{couponUrl}}" isSearch="{{isSearch}}" isContextCoupon="{{isContextCoupon}}"',
              'src="{{appiedCouponData.images.rateCouponNegative}}"',
              'onmouseover="this.src=\'{{appiedCouponData.images.rateCouponNegativeHover}}\'"',
              'onmouseout="this.src=\'{{appiedCouponData.images.rateCouponNegative}}\'"/>',
          '{{/appiedCouponData}}',
          '{{^appiedCouponData}}',
            '<div class="asp-coupon-rate-thanks" resurl="{{url}}">{{panelData.strings.spRateCouponsThanks}}</div>',
            '<img ondragstart="return false;" class="asp-coupon-rate-positive"  resurl="{{url}}" isSearch="{{isSearch}}" isContextCoupon="{{isContextCoupon}}"',
              'src="{{panelData.images.rateCouponPositive}}"',
              'onmouseover="this.src=\'{{panelData.images.rateCouponPositiveHover}}\'"',
              'onmouseout="this.src=\'{{panelData.images.rateCouponPositive}}\'"/>',
            '<img ondragstart="return false;" class="asp-coupon-rate-negative"  resurl="{{url}}" isSearch="{{isSearch}}" isContextCoupon="{{isContextCoupon}}"',
              'src="{{panelData.images.rateCouponNegative}}"',
              'onmouseover="this.src=\'{{panelData.images.rateCouponNegativeHover}}\'"',
              'onmouseout="this.src=\'{{panelData.images.rateCouponNegative}}\'"/>',
          '{{/appiedCouponData}}',
        '</div>',
      '</div>',
    ],
    couponTop:[
      '<div class="asp-coupon-top">',
        '<div class="asp-coupon-item-value">',
          '{{#value}}',
            '<div class="asp-coupon-item-value-save">{{panelData.strings.save}}</div>',
            '<div class="asp-coupon-item-value-text" title="{{value}}">{{value}}</div>',
          '{{/value}}',
          '{{^value}}',
            '<img class="asp-coupon-img-placeholder" ondragstart="return false;" src="{{panelData.images.couponsDefault}}" onerror="this.src=\'{{panelData.images.couponsDefault}}\';"/>',
          '{{/value}}',
        '</div>',
        '<div class="asp-coupon-item-label">{{title}}</div>',
        '{{#affiliate}}',
          '<div class="asp-coupon-affiliate">{{affiliate}}</div>',
        '{{/affiliate}}',
        '{{#text}}',
          '<div class="asp-coupon-description">',
            {temp: "couponDescText"},
          '</div>',
        '{{/text}}',
      '</div>',
    ],
    selectedCoupon:[
      '<div class="asp-coupon-item-active{{#code}}-with-code{{/code}}" id="coupon" resurl="{{url}}" isSearch="{{isSearch}}" isContextCoupon="{{isContextCoupon}}">',
        {temp: 'couponTop'},
        {temp: 'dashedLineSeparator'},
        '{{#code}}',
          '<div class="asp-coupon-bottom-with-code" cupcod="{{code}}">',
            '<div class="asp-coupon-item-copy-code" resurl="{{url}}" isSearch="{{isSearch}}" isContextCoupon="{{isContextCoupon}}">{{{spClickThenPaste}}}</div>',
            '<div class="asp-coupon-item-coupon-code">',
              '<div class="asp-coupon-item-coupon-code-text asp-code-opacity" resurl="{{url}}" isSearch="{{isSearch}}" cupcod="{{code}}" isContextCoupon="{{isContextCoupon}}">{{code}}</div>',
              '<div class="asp-coupon-item-coupon-code-text-copied">{{panelData.strings.spCodeCopied}}</div>',
            '</div>',
            '{{^panelData.browserType.isFirefox}}',
              '{{^rated}}',
                {temp: "rateAppliedCoupons"},
              '{{/rated}}',
            '{{/panelData.browserType.isFirefox}}',
          '</div>',
        '{{/code}}',
        '{{^code}}',
          '<div class="asp-coupon-bottom-without-code">',
            '<div class="asp-coupon-item-coupon-applied" resurl="{{url}}" isSearch="{{isSearch}}" isContextCoupon="{{isContextCoupon}}">{{{spSearchCouponAppliedOnPage}}}</div>',
            '{{^panelData.browserType.isFirefox}}',
              '{{^rated}}',
                {temp: "rateAppliedCoupons"},
              '{{/rated}}',
            '{{/panelData.browserType.isFirefox}}',
          '</div>',
        '{{/code}}',
      '</div>',
    ],
    separatorTextSecond: [
      '{{#vouchersAvailable}}<div class="asp-separator-text {{#selectedCouponAnimation}}asp-separator-text-hidden{{/selectedCouponAnimation}}">{{panelData.strings.spAvailableCoupons}}</div>{{/vouchersAvailable}}',
    ],
    singleCoupon:[
      '<div class="asp-coupon-item" id="coupon" resurl="{{url}}" isSearch="{{isSearch}}" isContextCoupon="{{isContextCoupon}}">',
        {temp: 'couponTop'},
        '<div class="asp-coupon-bottom"  id="coupon" resurl="{{url}}" isSearch="{{isSearch}}" isContextCoupon="{{isContextCoupon}}">',
          '<div class="asp-coupon-item-get-coupon">',
            '<div class="asp-coupon-item-get-coupon-button">',
              '{{#code}}{{panelData.strings.spGetCouponCode}}{{/code}}',
              '{{^code}}{{panelData.strings.spApply}}{{/code}}',
            '</div>',
          '</div>',
        '</div>',
      '</div>',
    ],
    notSelectedCoupons:[
      '{{#coupons}}',
        '{{^selected}}',
          {temp: 'singleCoupon'},
        '{{/selected}}',
      '{{/coupons}}',
    ],
    selectedCoupons: [
      '{{#coupons}}',
        '{{#selected}}',
          {temp: 'selectedCoupon'},
        '{{/selected}}',
      '{{/coupons}}'
    ],
    couponsWrapper:[
      '{{#vouchersSelected}}',
        {temp: 'separatorTextFirst'},
        {temp: 'selectedCoupons'},
        {temp: 'separatorTextSecond'},
        {temp: 'notSelectedCoupons'},
      '{{/vouchersSelected}}',
      '{{^vouchersSelected}}',
        {temp: 'separatorTextSecond'},
        {temp: 'notSelectedCoupons'},
      '{{/vouchersSelected}}',
      '{{#social.showInBottomCoupons}}',
        {temp: 'socialSharing'},
      '{{/social.showInBottomCoupons}}',
    ],
    panelSecurity:[
      '<div class="a-sp-panel-security" id="a-sp-panel-security">',
        {temp: "security"},
        {temp: "securityWithFeedback"},
      '</div>',
    ],
    resizeBar:[
      '<div class="a-sp-items-wrapper-resize" id="panel-resize">',
        '<div class="a-sp-resize-handle-1"></div>',
        '<div class="a-sp-resize-handle-2"></div>',
      '</div>',
    ],
    othersWrapper:[
      '<div id="othersWrapper">',
        '{{#redirectLength}}',
            '<div class="asp-separator-text-first">{{panelData.strings.spAvailableOthers}}</div>',
            '{{#redirects}}',
              {temp: "redirectItem"},
            '{{/redirects}}',
        '{{/redirectLength}}',
      '</div>',
    ],
    redirectItem:[
      '<div class="asp-redirect-item" id="redirect" resurl="{{url}}">',
        '<div class="asp-redirect-top">',
          '<div class="asp-redirect-item-image">',
            '{{^secondaryImage}}',
              '<img ondragstart="return false;" class="asp-redirect-default-img" src="{{panelData.images.specialDealsGIF}}" onerror="this.src=\'{{panelData.images.specialDealsGIF}}\';"/>',
            '{{/secondaryImage}}',
            '{{#secondaryImage}}',
              '<img ondragstart="return false;" class="asp-redirect-default-img" id="redirectImage" src="{{secondaryImage}}" onerror="this.src=\'{{panelData.images.redirectPlaceholderBig}}\';"/>',
            '{{/secondaryImage}}',
          '</div>',
          '<div class="asp-redirect-item-label">',
            '<div class="asp-redirect-item-label-text">{{{title}}}</div>',
          '</div>',
          '<div class="asp-redirect-description">',
            '<div class="asp-redirect-description-text">{{{availability}}}</div>',
          '</div>',
        '</div>',
        '{{^formattedPrice}}',
          '<div class="asp-redirect-bottom">',
            '<div class="asp-redirect-button">{{buttonText}}</div>',
          '</div>',
        '{{/formattedPrice}}',
        '{{#formattedPrice}}',
          {temp: "dashedLineSeparator"},
          '<div class="asp-redirect-item-bottom-with-price">',
            '{{#primaryImage}}',
              '<img ondragstart="return false;" class="asp-redirect-item-bottom-img" src="{{primaryImage}}" />',
            '{{/primaryImage}}',
            '{{#saving}}',
              '<div class="asp-redirect-item-bottom-saving" style="background-image: url({{panelData.images.ribbonRedirect}});">',
                '<div class="asp-redirect-item-bottom-saving-text">{{saving}}</div>',
              '</div>',
            '{{/saving}}',
            '<div class="asp-redirect-item-bottom-price">{{formattedPrice}}</div>',
          '</div>',
        '{{/formattedPrice}}',
      '</div>',
  ],
    dashedLineSeparator: [
      '{{#panelData.images.dashedLine}}',
        '<div class="asp-dashed-separator">',
            '<img ondragstart="return false;" class="asp-dashed-separator-line" src="{{panelData.images.dashedLine}}" onerror="this.src=\'{{panelData.images.dashedLine}}\';"/>',
        '</div>',
      '{{/panelData.images.dashedLine}}',
      '{{^panelData.images.dashedLine}}{{#appiedCouponData.images.dashedLine}}',
        '<div class="asp-dashed-separator">',
            '<img ondragstart="return false;" class="asp-dashed-separator-line" src="{{appiedCouponData.images.dashedLine}}" onerror="this.src=\'{{appiedCouponData.images.dashedLine}}\';"/>',
        '</div>',
      '{{/appiedCouponData.images.dashedLine}}{{/panelData.images.dashedLine}}',
    ],
    starsRating: [
        '<div class="asp-rating-stars-wrapper">',
        '{{#stars}}',
        '<i class="asp-rating-star" style="background-image: url({{.}});"></i>',
        '{{/stars}}',
        '</div>'
    ],
    copiedToClipboard: [
      '{{#panelData.strings.sasCouponCodeCopied}}',
        '<div class="asp-copied-to-clipboard">{{panelData.strings.sasCouponCodeCopied}}</div>',
      '{{/panelData.strings.sasCouponCodeCopied}}',
      '{{^panelData.strings.sasCouponCodeCopied}}',
        '{{#appiedCouponData.strings.sasCouponCodeCopied}}',
          '<div class="asp-copied-to-clipboard">{{appiedCouponData.strings.sasCouponCodeCopied}}</div>',
        '{{/appiedCouponData.strings.sasCouponCodeCopied}}',
      '{{/panelData.strings.sasCouponCodeCopied}}',
    ],
    safeShopSettingsPopup : [
      '<div class="asp-settings-page">',
        '<div class="asp-settings-poppup">',
          '<div class="asp-settings-title-box">',
            '<div class="asp-settings-title-icon" style="background-image: url({{poppupSettings.images.logo}});"></div>',
            '<div class="asp-settings-title-text">',
              '{{#avastBranding}}',
                '{{poppupSettings.strings.spSettingsPageTitleAvast}}',
              '{{/avastBranding}}',
              '{{^avastBranding}}',
                '{{poppupSettings.strings.spSettingsPageTitleAvg}}',
              '{{/avastBranding}}',
            '</div>',
            '<div class="asp-settings-title-close" id="asp-popup-settings-close" style="background-image: url({{poppupSettings.images.close}});"></div>',
          '</div>',
          '<div class="asp-middle-box">',
            '<div class="asp-middle-menu">',
              '<div class="asp-middle-item-notifications{{#poppupSettings.menuOpt.notifications.selected}}-selected{{/poppupSettings.menuOpt.notifications.selected}}" id="sp-menu-notifications">',
                '{{poppupSettings.strings.spSettingsTabNotifications}}',
              '</div>',
              '<div class="asp-middle-item-custom-list{{#poppupSettings.menuOpt.customList.selected}}-selected{{/poppupSettings.menuOpt.customList.selected}}" id="sp-menu-customList">',
                '{{poppupSettings.strings.spSettingsPageCustomList}}',
              '</div>',
              '<div class="asp-middle-item-privacy{{#poppupSettings.menuOpt.privacy.selected}}-selected{{/poppupSettings.menuOpt.privacy.selected}}" id="sp-menu-privacy">',
                 '{{poppupSettings.strings.spSettingsPrivacy}}',
               '</div>',
              '<div class="asp-middle-item-help{{#poppupSettings.menuOpt.help.selected}}-selected{{/poppupSettings.menuOpt.help.selected}}" id="sp-menu-help">',
                '{{poppupSettings.strings.spSettingsPageHelp}}',
            '</div>',
            '</div>',
            '<div class="asp-middle-options">',
              '<div class="asp-middle-panel-notifications {{#poppupSettings.menuOpt.notifications.selected}}asp-display-grid{{/poppupSettings.menuOpt.notifications.selected}}" id="sp-panel-notifications-options">',
                '<div class="asp-tabs">',
                  '<div class="asp-offers-tab-selected" id="tabOffer">',
                    '{{poppupSettings.strings.spSettingsTabNotificationsOffers}}',
                  '</div>',
                  '<div class="asp-coupons-tab" id="tabCoupon">',
                    '{{poppupSettings.strings.spSettingsTabNotificationsCoupons}}',
                  '</div>',
                  '<div class="asp-others-tab"  id="tabOther">',
                  '{{poppupSettings.strings.spSettingsTabNotificationsOthers}}',
                  '</div>',
                '</div>',
                '<div class="asp-tabs-content-selected" id="contentOffers">',
                  '<div class="asp-title-offers">',
                    '{{poppupSettings.strings.spSettingsTabNotificationsOffersTitle}}',
                  '</div>',
                  '<div class="asp-offers-show-all{{#poppupSettings.menuOpt.notifications.offers.showAlways}}-selected{{/poppupSettings.menuOpt.notifications.offers.showAlways}}" id="offersShowAll">',
                    '<div class="asp-radio-button">',
                    '</div>',
                    '<div class="asp-desc">',
                      '{{poppupSettings.strings.spSettingsTabNotificationsOffersShowAll}}',
                    '</div>',
                  '</div>',
                  '<div class="asp-offers-show-better{{#poppupSettings.menuOpt.notifications.offers.showBetter}}-selected{{/poppupSettings.menuOpt.notifications.offers.showBetter}}" id="offersShowBetter">',
                    '<div class="asp-radio-button">',
                    '</div>',
                    '<div class="asp-desc">',
                      '{{poppupSettings.strings.spSettingsTabNotificationsOffersBetter}}',
                    '</div>',
                  '</div>',
                  '<div class="asp-offers-hide{{#poppupSettings.menuOpt.notifications.offers.hide}}-selected{{/poppupSettings.menuOpt.notifications.offers.hide}}" id="offersHide">',
                      '<div class="asp-radio-button">',
                      '</div>',
                      '<div class="asp-desc">',
                        '{{poppupSettings.strings.spSettingsTabNotificationsOffersHideAll}}',
                      '</div>',
                      '<div class="asp-radio-button-option-desc">',
                        '{{poppupSettings.strings.spSettingsTabNotificationsOffersHideAllDesc}}',
                      '</div>',
                  '</div>',
                  '<div class="asp-title-accommodations">',
                    '{{poppupSettings.strings.spSettingsTabNotificationAccommodationsTitle}}',
                  '</div>',
                  '<div class="asp-accommodations-show-better" id="accommodationsShowBetter">',
                    '{{#poppupSettings.menuOpt.notifications.accommodations.showBetter}}',
                      '<div class="asp-check-box" style="background-image: url({{poppupSettings.images.checkboxChecked}});" id="checkboxAccommodationsShowBetter"></div>',
                    '{{/poppupSettings.menuOpt.notifications.accommodations.showBetter}}',
                    '{{^poppupSettings.menuOpt.notifications.accommodations.showBetter}}',
                      '<div class="asp-check-box" style="background-image: url({{poppupSettings.images.checkbox}});" id="checkboxAccommodationsShowBetter"></div>',
                    '{{/poppupSettings.menuOpt.notifications.accommodations.showBetter}}',
                    '<div class="asp-desc">',
                      '{{poppupSettings.strings.spSettingsTabNotificationsAccommodationsShowBetter}}',
                    '</div>',
                  '</div>',
                  '<div class="asp-accommodations-show-similar" id="accommodationsShowSimilar">',
                    '{{#poppupSettings.menuOpt.notifications.accommodations.showSimilar}}',
                      '<div class="asp-check-box" style="background-image: url({{poppupSettings.images.checkboxChecked}});" id="checkboxAccommodationsShowSimilar"></div>',
                    '{{/poppupSettings.menuOpt.notifications.accommodations.showSimilar}}',
                    '{{^poppupSettings.menuOpt.notifications.accommodations.showSimilar}}',
                      '<div class="asp-check-box" style="background-image: url({{poppupSettings.images.checkbox}});" id="checkboxAccommodationsShowSimilar"></div>',
                    '{{/poppupSettings.menuOpt.notifications.accommodations.showSimilar}}',
                    '<div class="asp-desc">',
                      '{{poppupSettings.strings.spSettingsTabNotificationsAccommodationsSimilar}}',
                    '</div>',
                  '</div>',
                  '<div class="asp-accommodations-show-popular" id="accommodationsShowPopular">',
                    '{{#poppupSettings.menuOpt.notifications.accommodations.showPopular}}',
                      '<div class="asp-check-box" style="background-image: url({{poppupSettings.images.checkboxChecked}});" id="checkboxAccommodationsShowPopular"></div>',
                    '{{/poppupSettings.menuOpt.notifications.accommodations.showPopular}}',
                    '{{^poppupSettings.menuOpt.notifications.accommodations.showPopular}}',
                      '<div class="asp-check-box" style="background-image: url({{poppupSettings.images.checkbox}});" id="checkboxAccommodationsShowPopular"></div>',
                    '{{/poppupSettings.menuOpt.notifications.accommodations.showPopular}}',
                    '<div class="asp-desc">',
                      '{{poppupSettings.strings.spSettingsTabNotificationsAccommodationsPopular}}',
                    '</div>',
                  '</div>',
                '</div>',
                '<div class="asp-tabs-content" id="contentCoupons">',
                  '<div class="asp-title-coupons">',
                    '{{poppupSettings.strings.spSettingsTabNotificationsCoupons}}',
                  '</div>',
                  '<div class="asp-coupons-show-all{{#poppupSettings.menuOpt.notifications.coupons.showAlways}}-selected{{/poppupSettings.menuOpt.notifications.coupons.showAlways}}" id="couponsShowAll">',
                    '<div class="asp-radio-button">',
                    '</div>',
                    '<div class="asp-desc">',
                      '{{poppupSettings.strings.spSettingsTabNotificationsCouponsShowAll}}',
                    '</div>',
                  '</div>',
                  '<div class="asp-coupons-show-once{{#poppupSettings.menuOpt.notifications.coupons.showOnce}}-selected{{/poppupSettings.menuOpt.notifications.coupons.showOnce}}" id="couponsShowOnce">',
                    '<div class="asp-radio-button">',
                    '</div>',
                    '<div class="asp-desc">',
                      '{{poppupSettings.strings.spSettingsTabNotificationsCouponsShowOnce}}',
                    '</div>',
                  '</div>',
                  '<div class="asp-coupons-hide{{#poppupSettings.menuOpt.notifications.coupons.hide}}-selected{{/poppupSettings.menuOpt.notifications.coupons.hide}}" id="couponsHide">',
                      '<div class="asp-radio-button">',
                      '</div>',
                      '<div class="asp-desc">',
                        '{{poppupSettings.strings.spSettingsTabNotificationsCouponsHide}}',
                      '</div>',
                      '<div class="asp-radio-button-option-desc">',
                        '{{poppupSettings.strings.spSettingsTabNotificationsCouponsHideDesc}}',
                      '</div>',
                  '</div>',
                '</div>',
                '<div class="asp-tabs-content" id="contentOthers">',
                  '<div class="asp-title-others">',
                    '{{poppupSettings.strings.spSettingsTabNotificationsOthers}}',
                  '</div>',
                  '<div class="asp-others-show-all" id="othersShowAll">',
                    '{{#poppupSettings.menuOpt.notifications.others.showAlways}}',
                      '<div class="asp-check-box" style="background-image: url({{poppupSettings.images.checkboxChecked}});" id="checkboxOthersShowAll"></div>',
                    '{{/poppupSettings.menuOpt.notifications.others.showAlways}}',
                    '{{^poppupSettings.menuOpt.notifications.others.showAlways}}',
                      '<div class="asp-check-box" style="background-image: url({{poppupSettings.images.checkbox}});" id="checkboxOthersShowAll"></div>',
                    '{{/poppupSettings.menuOpt.notifications.others.showAlways}}',
                    '<div class="asp-desc">',
                      '{{poppupSettings.strings.spSettingsTabNotificationsOthersDesc}}',
                    '</div>',
                  '</div>',
                '</div>',
              '</div>',
              '<div class="asp-middle-panel-custom-list {{#poppupSettings.menuOpt.customList.selected}}asp-display-grid{{/poppupSettings.menuOpt.customList.selected}}"  id="sp-panel-customList-options">',
                '<div class="asp-p-cl-title">',
                  '{{poppupSettings.strings.spSettingsPageCustomListTitle}}',
                '</div>',
                '<div class="asp-p-cl-title-desc">',
                  '{{poppupSettings.strings.spSettingsPageCustomListTitleDesc}}',
                '</div>',
                '<div class="asp-p-cl-add-site-button {{#poppupSettings.menuOpt.customList.showAddButton}}asp-display-block{{/poppupSettings.menuOpt.customList.showAddButton}}" id="add-site-button-to-box">',
                  '<div class="asp-p-cl-add-site-button-icon" style="background-image: url({{poppupSettings.images.add}});"></div>',
                  '<div class="asp-p-cl-add-site-button-text">',
                    '{{poppupSettings.strings.spSettingsPageCustomListItemAddSite}}',
                '</div>',
                '</div>',
                '<div class="asp-p-cl-add-site-box {{^poppupSettings.menuOpt.customList.showAddButton}}asp-display-block{{/poppupSettings.menuOpt.customList.showAddButton}}" id="add-site-box">',
                  '<input type="text" class="asp-p-cl-add-site-text" id="new-site-name" autofocus>',
                  '<div class="asp-p-cl-add-site-add" id="add-site-add">',
                    '{{poppupSettings.strings.spSettingsPageCustomListItemAdd}}',
                  '</div>',
                  '<div class="asp-p-cl-add-site-cancel" id="add-site-cancel">',
                    '{{poppupSettings.strings.spSettingsPageCancel}}',
                  '</div>',
                '</div>',
                '<div class="asp-p-cl-sites-box">',
                  '{{#poppupSettings.menuOpt.customList.whiteList.length}}',
                    '{{#poppupSettings.menuOpt.customList.whiteList}}',
                      '<div class="asp-p-cl-box-element">',
                        '<div class="asp-p-cl-box-element-text">',
                          '{{.}}',
                        '</div>',
                        '<div class="asp-p-cl-box-element-close" style="background-image: url({{poppupSettings.images.erase}});">',
                        '</div>',
                      '</div>',
                    '{{/poppupSettings.menuOpt.customList.whiteList}}',
                  '{{/poppupSettings.menuOpt.customList.whiteList.length}}',
                '</div>',
              '</div>',
              '<div class="asp-middle-panel-privacy {{#poppupSettings.menuOpt.privacy.selected}}asp-display-grid{{/poppupSettings.menuOpt.privacy.selected}}"  id="sp-panel-privacy-options">',
                 '<div class="asp-middle-panel-privacy-title">',
                    '{{poppupSettings.strings.spSettingsPrivacy}}',
                 '</div>',
                  '<div class="asp-middle-panel-privacy-checkbox">',
                    '{{#poppupSettings.menuOpt.privacy.accepted}}',
                        '<div class="asp-check-box asp-middle-panel-privacy-image" style="background-image: url({{poppupSettings.images.checkboxChecked}});" id="checkboxPrivacy"></div>',
                    '{{/poppupSettings.menuOpt.privacy.accepted}}',
                    '{{^poppupSettings.menuOpt.privacy.accepted}}',
                        '<div class="asp-check-box asp-middle-panel-privacy-image" style="background-image: url({{poppupSettings.images.checkbox}});" id="checkboxPrivacy"></div>',
                    '{{/poppupSettings.menuOpt.privacy.accepted}}',
                    '<div class="asp-middle-panel-privacy-checkbox-text">',
                        '{{poppupSettings.strings.spSettingsPrivacyNotice}}',
                    '</div>',
                  '</div>',
              '</div>',
              '<div class="asp-middle-panel-help {{#poppupSettings.menuOpt.help.selected}}asp-display-grid{{/poppupSettings.menuOpt.help.selected}}"  id="sp-panel-help-options">',
                '<div class= "asp-help-group-1">',
                  '<div class= "asp-help-title">{{poppupSettings.strings.spSettingsPageHelpNotificationsTitle}}</div>',
                  '<div class= "asp-help-title-desc">{{poppupSettings.strings.spSettingsPageHelpNotificationsTitleDesc}}</div>',
                '</div>',
                '<div class= "asp-help-group-2">',
                  '<div class= "asp-help-title">{{poppupSettings.strings.spSettingsPageHelpOffersTitle}}</div>',
                  '<div class= "asp-help-title-desc">{{poppupSettings.strings.spSettingsPageHelpOffersTitleDesc}}</div>',
                '</div>',
                '<div class= "asp-help-group-3">',
                  '<div class= "asp-help-title">{{poppupSettings.strings.spSettingsPageHelpCouponsTitle}}</div>',
                  '<div class= "asp-help-title-desc">{{poppupSettings.strings.spSettingsPageHelpCouponsTitleDesc}}</div>',
                '</div>',
                '<div class= "asp-help-group-4">',
                  '<div class= "asp-help-title">{{poppupSettings.strings.spSettingsPageHelpOthersTitle}}</div>',
                  '<div class= "asp-help-title-desc">{{poppupSettings.strings.spSettingsPageHelpOthersTitleDesc}}</div>',
                '</div>',
                '<div class= "asp-help-faqs">{{{poppupSettings.strings.spSettingsPageHelpFAQsTitle}}}</div>',
              '</div>',
            '</div>',
          '</div>',
          '<div class="asp-settings-footer-box">',
            '<div class="asp-settings-footer-cancel" id="asp-popup-settings-cancel">',
              '{{poppupSettings.strings.spSettingsPageCancel}}',
            '</div>',
            '<div class="asp-settings-footer-save" id="asp-poppup-settings-save">',
              '{{poppupSettings.strings.spSettingsPageSave}}',
            '</div>',
          '</div>',
        '</div>',
      '</div>',
    ],
    whiteListElement : [
      '<div class="asp-p-cl-box-element">',
        '<div class="asp-p-cl-box-element-text">',
          '{{site}}',
        '</div>',
        '<div class="asp-p-cl-box-element-close" style="background-image: url({{icon}});">',
        '</div>',
      '</div>',
    ],
    // bar notifications
    notificationBar: [
      '<div class="asp-notifications-bar" id="asp-notifications-bar">',
        '<img ondragstart="return false;" class="asp-notifications-bar-logo" src="{{panelData.images.logo}}" onerror="this.src=\'{{panelData.images.logo}}\';"/>',
        '{{#notifications.activeNotification.isSpecialDeal}}',
          {temp: "notificationRedirectBar"},
        '{{/notifications.activeNotification.isSpecialDeal}}',
        '{{^notifications.activeNotification.isSpecialDeal}}',
          {temp: "notificationSimpleBar"},
        '{{/notifications.activeNotification.isSpecialDeal}}',
        '<div class="asp-notifications-bar-actions">',
        '<div class="asp-notifications-bar-gear-icon" style="background-image: url({{panelData.images.settings}});"></div>',
        '<div class="asp-notifications-bar-close-icon" style="background-image: url({{panelData.images.close}});"></div>',
      '</div>',
    '</div>',
    ],
    notificationSimpleBar: [
      '<div class="asp-notifications-bar-content">',
        '{{#notifications.activeNotification.isOffer}}',
            '<img ondragstart="return false;" class="asp-notifications-bar-image" src="{{panelData.images.moreOffersBar}}" onerror="this.src=\'{{panelData.images.moreOffersBar}}\';"/>',
            '<img ondragstart="return false;" class="asp-notifications-bar-image-animated asp-notification-bar-image-hidden" src="{{panelData.animations.moreOffersBar}}" onerror="this.src=\'{{panelData.animations.moreOffersBar}}\';"/>',
            '<div class="asp-notifications-bar-text">{{panelData.strings.spBetterOffersNotificationBarMessage}}</div>',
        '{{/notifications.activeNotification.isOffer}}',
        '{{#notifications.activeNotification.isAccommodations}}',
            '<img ondragstart="return false;" class="asp-notifications-bar-image" src="{{panelData.images.moreOffersBar}}" onerror="this.src=\'{{panelData.images.moreOffersBar}}\';"/>',
            '<img ondragstart="return false;" class="asp-notifications-bar-image-animated asp-notification-bar-image-hidden" src="{{panelData.animations.moreOffersBar}}" onerror="this.src=\'{{panelData.animations.moreOffersBar}}\';"/>',
            '<div class="asp-notifications-bar-text">{{panelData.strings.spBetterOffersNotificationBarMessage}}</div>',
        '{{/notifications.activeNotification.isAccommodations}}',
        '{{#notifications.activeNotification.isAlternativeHotel}}',
            '<img ondragstart="return false;" class="asp-notifications-bar-image" src="{{panelData.images.hotelsBar}}" onerror="this.src=\'{{panelData.images.hotelsBar}}\';"/>',
            '<img ondragstart="return false;" class="asp-notifications-bar-image-animated asp-notification-bar-image-hidden" src="{{panelData.animations.hotelsBar}}" onerror="this.src=\'{{panelData.animations.hotelsBar}}\';"/>',
            '<div class="asp-notifications-bar-text">{{panelData.strings.spSimilarHotelsNotificationMessage}}</div>',
        '{{/notifications.activeNotification.isAlternativeHotel}}',
        '{{#notifications.activeNotification.isPopularHotel}}',
            '<img ondragstart="return false;" class="asp-notifications-bar-image" src="{{panelData.images.hotelsBar}}" onerror="this.src=\'{{panelData.images.hotelsBar}}\';"/>',
            '<img ondragstart="return false;" class="asp-notifications-bar-image-animated asp-notification-bar-image-hidden" src="{{panelData.animations.hotelsBar}}" onerror="this.src=\'{{panelData.animations.hotelsBar}}\';"/>',
            '<div class="asp-notifications-bar-text">{{panelData.strings.spCityHotelNotificationMessage}}<span class="asp-notifications-bar-city-text">{{cityName}}</span></div>',
        '{{/notifications.activeNotification.isPopularHotel}}',
        '{{#notifications.activeNotification.isCoupon}}',
            '<img ondragstart="return false;" class="asp-notifications-bar-image" src="{{panelData.images.couponsBar}}" onerror="this.src=\'{{panelData.images.couponsBar}}\';"/>',
            '<img ondragstart="return false;" class="asp-notifications-bar-image-animated asp-notification-bar-image-hidden" src="{{panelData.animations.couponsBar}}" onerror="this.src=\'{{panelData.animations.couponsBar}}\';"/>',
            '<div class="asp-notifications-bar-text">{{panelData.strings.spCouponsNotificationMessage}}</div>',
        '{{/notifications.activeNotification.isCoupon}}',
        '{{#notifications.activeNotification.isOfferAndCoupon}}',
            '<img ondragstart="return false;" class="asp-notifications-bar-image" src="{{panelData.images.offersAndCouponsBar}}" onerror="this.src=\'{{panelData.images.offersAndCouponsBar}}\';"/>',
            '<img ondragstart="return false;" class="asp-notifications-bar-image-animated asp-notification-bar-image-hidden" src="{{panelData.animations.offersAndCouponsBar}}" onerror="this.src=\'{{panelData.animations.offersAndCouponsBar}}\';"/>',
            '<div class="asp-notifications-bar-text">{{panelData.strings.spOffersAndCouponsNotificationMessage}}</div>',
        '{{/notifications.activeNotification.isOfferAndCoupon}}',
        '{{#notifications.activeNotification.isAccommodationsAndCoupon}}',
            '<img ondragstart="return false;" class="asp-notifications-bar-image" src="{{panelData.images.offersAndCouponsBar}}" onerror="this.src=\'{{panelData.images.offersAndCouponsBar}}\';"/>',
            '<img ondragstart="return false;" class="asp-notifications-bar-image-animated asp-notification-bar-image-hidden" src="{{panelData.animations.offersAndCouponsBar}}" onerror="this.src=\'{{panelData.animations.offersAndCouponsBar}}\';"/>',
            '<div class="asp-notifications-bar-text">{{panelData.strings.spOffersAndCouponsNotificationMessage}}</div>',
        '{{/notifications.activeNotification.isAccommodationsAndCoupon}}',
        '<div class="asp-notifications-bar-button">',
            '<span class="asp-notifications-bar-button-text">{{panelData.strings.spShowNotificationMessage}}</span>',
            '<span class="asp-notifications-bar-button-badge">',
              '<div class="asp-notifications-bar-button-badge-text">{{detailsToClosed.offerNumber}}</div>',
            '</span>',
        '</div>',
      '</div>',
    ],
    notificationRedirectBar:[
      '<div class="asp-notifications-bar-content-redirect">',
        '<div class="asp-notification-bar-title">{{panelData.strings.spShowNotificationRedirectMessage}}</div>',
        '<div class="asp-notifications-bar-redirect">',
          '<div class="asp-notifications-bar-redirect-deal">',
            '{{#redirects.0.barImage}}',
              '<img ondragstart="return false;" class="asp-notifications-bar-redirect-deal-img" src="{{redirects.0.barImage}}" onerror="this.src=\'{{panelData.images.redirectPlaceholder}}\';"/>',
            '{{/redirects.0.barImage}}',
            '{{^redirects.0.barImage}}',
              '<div class="asp-blank-div"></div>',
            '{{/redirects.0.barImage}}',
            '<div class="asp-notifications-bar-redirect-deal-description">',
              '<div class="asp-notifications-bar-redirect-deal-title">{{{redirects.0.title}}}</div>',
              '<div class="asp-notifications-bar-redirect-deal-subtitle">{{{redirects.0.availability}}}</div>',
            '</div>',
            '<div class="asp-notification-bar-redirect-deal-info-wrapper">',
            '</div>',
          '</div>',
          '<div class="asp-notifications-bar-button" resurl="{{redirects.0.url}}">',
            '<span class="asp-notifications-bar-button-text">{{panelData.strings.spNotificationRedirectShowRedirectMessage}}</span>',
            '<img ondragstart="return false;" class="asp-notifications-bar-button-arrow" src="{{panelData.images.arrow}}" onerror="this.src=\'{{panelData.images.arrow}}\';"/>',
          '</div>',
        '</div>',
      '</div>',
    ],
    // feedback
    feedback: [
        '<div class="a-sp-feedback a-sp-feedback-hidden" id="a-sp-feedback-container">',
          {temp: "feedbackQuestionContainer"},
          {temp: "feedbackPositiveReactionContainer"},
          {temp: "feedbackNegativeReactionContainer"},
        '</div>'
    ],
    feedbackQuestionContainer: [
        '<div id="a-sp-feedback-action-question" class="a-sp-feedback-question">',
          '<img ondragstart="return false;" class="a-sp-feedback-question-logo" src="{{templateData.images.logoSP32x32}}" onerror="this.src=\'{{templateData.images.logoSP32x32}}\';"/>',
          '<p class="a-sp-feedback-question-text">{{#templateData.isAvast}}{{{templateData.strings.safePriceEnjoyQuestion_Avast}}}{{/templateData.isAvast}}{{^templateData.isAvast}}{{{templateData.strings.safePriceEnjoyQuestion_AVG}}}{{/templateData.isAvast}}</p>',
          '<div class="a-sp-feedback-question-buttons-container">',
              '<div class="a-sp-feedback-question-buttons-yes">{{{templateData.strings.sasAnswerYes}}}</div>',
              '<div class="a-sp-feedback-question-buttons-no">{{{templateData.strings.sasAnswerNo}}}</div>',
          '</div>',
          '<div class="a-sp-feedback-question-later">{{{templateData.strings.safePriceAskMeLater}}}</div>',
        '</div>'
    ],
    feedbackPositiveReactionContainer: [
        '<div id="a-sp-feedback-action-positive" class="a-sp-feedback-action a-sp-feedback-hidden">',
          '<div class="a-sp-feedback-action-header">',
              '<div></div>',
              '<img ondragstart="return false;" id="a-sp-feedback-action-close-positive" class="a-sp-feedback-action-close-img" src="{{templateData.images.closeIcon}}" onerror="this.src=\'{{templateData.images.closeIcon}}\';"/>',
          '</div>',
          '<div class="a-sp-feedback-action-img-container">',
              '<img ondragstart="return false;" class="a-sp-feedback-action-img" src="{{templateData.images.positiveFeedback}}" onerror="this.src=\'{{templateData.images.positiveFeedback}}\';"/>',
          '</div>',
          '<div class="a-sp-feedback-action-text-container">',
              '<span class="a-sp-feedback-action-text-content">{{{templateData.strings.sasGladYouLike}}}</span>',
          '</div>',
          '<div class="a-sp-feedback-action-description-container">',
            '<span class="a-sp-feedback-action-description-content">{{{templateData.strings.safePriceLeaveRating}}}</span>',
          '</div>',
          '<div class="a-sp-feedback-action-button-container">',
            '<span id="a-sp-feedback-action-button-positive" class="a-sp-feedback-action-button-content">{{{templateData.strings.sasRate}}}</span>',
          '</div>',
        '</div>'
    ],
    feedbackNegativeReactionContainer: [
        '<div id="a-sp-feedback-action-negative" class="a-sp-feedback-action a-sp-feedback-hidden">',
          '<div class="a-sp-feedback-action-header">',
              '<div></div>',
              '<img ondragstart="return false;" id="a-sp-feedback-action-close-negative" class="a-sp-feedback-action-close-img" src="{{templateData.images.closeIcon}}" onerror="this.src=\'{{templateData.images.closeIcon}}\';"/>',
          '</div>',
          '<div class="a-sp-feedback-action-img-container">',
              '<img ondragstart="return false;" class="a-sp-feedback-action-img" src="{{templateData.images.negativeFeedback}}" onerror="this.src=\'{{templateData.images.negativeFeedback}}\';"/>',
          '</div>',
          '<div class="a-sp-feedback-action-text-container">',
              '<span class="a-sp-feedback-action-text-content">{{{templateData.strings.sasSorry}}}</span>',
          '</div>',
        '</div>'
    ],
    // social card
    socialSharing: [
        '<div class="a-sp-social" id="a-sp-social-container">',
          '<div class="a-sp-social-close-container">',
              '<img ondragstart="return false;" class="a-sp-social-close-img" src="{{{panelData.socialSharing.templateData.images.closeIcon12x12}}}" onerror="this.src=\'{{panelData.socialSharing.templateData.images.closeIcon12x12}}\';"/>',
          '</div>',
          '<div class="a-sp-social-title-container">',
            '{{{panelData.socialSharing.templateData.strings.spSocialShare}}}',
          '</div>',
          '<div class="a-sp-social-buttons-container">',
            '<div class="a-sp-social-buttons-fb-container">',
                '<img ondragstart="return false;" class="a-sp-social-buttons-fb-img" src="{{{panelData.socialSharing.templateData.images.fbLogo5x11}}}" onerror="this.src=\'{{panelData.socialSharing.templateData.images.fbLogo5x11}}\';"/>',
                '<img ondragstart="return false;" class="a-sp-social-buttons-fb-img-action a-sp-social-hidden" src="{{{panelData.socialSharing.templateData.images.fbLogo5x11HoverAndActive}}}" onerror="this.src=\'{{panelData.socialSharing.templateData.images.fbLogo5x11HoverAndActive}}\';"/>',
                '<span class="a-sp-social-buttons-fb-text">{{{panelData.socialSharing.templateData.strings.spSocialShareFb}}}</span>',
            '</div>',
            '<div class="a-sp-social-buttons-tttr-container">',
              '<img ondragstart="return false;" class="a-sp-social-buttons-tttr-img" src="{{{panelData.socialSharing.templateData.images.tttrLogo5x11}}}" onerror="this.src=\'{{panelData.socialSharing.templateData.images.tttrLogo5x11}}\';"/>',
              '<img ondragstart="return false;" class="a-sp-social-buttons-tttr-img-action a-sp-social-hidden" src="{{{panelData.socialSharing.templateData.images.tttrLogo5x11HoverAndActive}}}" onerror="this.src=\'{{panelData.socialSharing.templateData.images.tttrLogo5x11HoverAndActive}}\';"/>',
              '<span class="a-sp-social-buttons-tttr-text">{{{panelData.socialSharing.templateData.strings.spSocialShareFb}}}</span>',
            '</div>',
          '</div>',
        '</div>'
    ],
    closeTooltip: [
        '<div class="a-sp-close-tooltip" id="a-sp-close-tooltip-container">',
          '<div class="a-sp-close-tooltip-img-container">',
            '<img ondragstart="return false;" class="a-sp-close-tooltip-img" src="{{templateData.images.closeTooltipImage}}" onerror="this.src=\'{{templateData.images.closeTooltipImage}}\';"/>',
          '</div>',
          '<div class="a-sp-close-tooltip-message">',
            '<span class="a-sp-close-tooltip-text">{{templateData.strings.spAfterCloseTooltip}}</span>',
          '</div>',
          '<div class="a-sp-close-tooltip-buttons-row">',
            '<div id="a-sp-close-tooltip-button-got-it" class="a-sp-close-tooltip-button">{{templateData.strings.spAfterCloseTooltipGotIt}}</div>',
          '</div>',
        '</div>'
    ],
    safeShopPanelMinNotification:[
      '<div class="asp-panel-min-notification" id="asp-panel-min-notification">',
        '<div class="asp-panel-min-header" id="a-panel-min-header">',
          '<img ondragstart="return false;" class="asp-header-logo" src="{{panelData.images.logo}}" onerror="this.src=\'{{panelData.images.logo}}\';"/>',
          '<div class="asp-header-message">',
            '{{#notifications.activeNotification.isOfferAndCoupon}}{{panelData.strings.spOffersAndCouponsNotificationMessage}}{{/notifications.activeNotification.isOfferAndCoupon}}',
            '{{#notifications.activeNotification.isOffer}}{{panelData.strings.spBetterOffersNotificationBarMessage}}{{/notifications.activeNotification.isOffer}}',
            '{{#notifications.activeNotification.isAccommodationsAndCoupon}}{{panelData.strings.spOffersAndCouponsNotificationMessage}}{{/notifications.activeNotification.isAccommodationsAndCoupon}}',
            '{{#notifications.activeNotification.isAccommodations}}{{panelData.strings.spBetterOffersNotificationBarMessage}}{{/notifications.activeNotification.isAccommodations}}',
            '{{#notifications.activeNotification.isPopularHotel}}{{panelData.strings.spCityHotelNotificationMessage}}&nbsp;<span class="asp-header-message-city">{{cityName}}</span>{{/notifications.activeNotification.isPopularHotel}}',
            '{{#notifications.activeNotification.isAlternativeHotel}}{{panelData.strings.spSimilarHotelsNotificationMessage}}{{/notifications.activeNotification.isAlternativeHotel}}',
            '{{#notifications.activeNotification.isCoupon}}{{panelData.strings.spCouponsNotificationMessage}}{{/notifications.activeNotification.isCoupon}}',
            '{{#notifications.activeNotification.isCheckoutCoupon}}{{panelData.strings.spCouponsNotificationMessage}}{{/notifications.activeNotification.isCheckoutCoupon}}',
            '{{#notifications.activeNotification.isSpecialDeal}}{{panelData.strings.spShowNotificationRedirectMessage}}{{/notifications.activeNotification.isSpecialDeal}}',
          '</div>',
          '<div class="asp-header-close" id="a-panel-min-close" style="background-image: url({{panelData.images.close}});"></div>',
        '</div>',
        '<div class="asp-panel-min-body">',
          '<div id="wrapperItemsPanelMinNotifications">',
            '{{#notifications.activeNotification.isAccommodationsAndCoupon}}',
              '{{#hotelsPriceComp.0}}',
                  {temp: "hotelItem"},
              '{{/hotelsPriceComp.0}}',
              '{{^hotelsPriceComp}}',
                '{{#accommodations.0}}',
                    {temp: "hotelItem"},
                '{{/accommodations.0}}',
              '{{/hotelsPriceComp}}',
            '{{/notifications.activeNotification.isAccommodationsAndCoupon}}',
            '{{#notifications.activeNotification.isOfferAndCoupon}}{{#products.0}}',
                {temp: "offerItem"},
            '{{/products.0}}{{/notifications.activeNotification.isOfferAndCoupon}}',
            '{{#notifications.activeNotification.isOffer}}{{#products.0}}',
                {temp: "offerItem"},
            '{{/products.0}}{{/notifications.activeNotification.isOffer}}',
            '{{#notifications.activeNotification.isAccommodations}}{{#accommodations.0}}',
                {temp: "hotelItem"},
            '{{/accommodations.0}}{{/notifications.activeNotification.isAccommodations}}',
            '{{#notifications.activeNotification.isPopularHotel}}{{#hotelsCity.0}}',
                {temp: "hotelItem"},
            '{{/hotelsCity.0}}{{/notifications.activeNotification.isPopularHotel}}',
            '{{#notifications.activeNotification.isAlternativeHotel}}{{#hotelsSimilar.0}}',
                {temp: "hotelItem"},
            '{{/hotelsSimilar.0}}{{/notifications.activeNotification.isAlternativeHotel}}',
            '{{#notifications.activeNotification.isCoupon}}{{#firstCouponNotApplied}}',
                {temp: 'singleCoupon'},
            '{{/firstCouponNotApplied}}{{/notifications.activeNotification.isCoupon}}',
            '{{#notifications.activeNotification.isCheckoutCoupon}}{{#firstCouponNotApplied}}',
                {temp: 'singleCoupon'},
            '{{/firstCouponNotApplied}}{{/notifications.activeNotification.isCheckoutCoupon}}',
            '{{#notifications.activeNotification.isSpecialDeal}}{{#redirects.0}}',
                {temp: "redirectItem"},
            '{{/redirects.0}}{{/notifications.activeNotification.isSpecialDeal}}',
          '</div>',
          '{{#showShowAllButton}}',
            '<div id="wrapperShowAllButtom">',
              '<div class="asp-button-show-all">',
                '<div class="asp-buttom-text">',
                  '{{panelData.strings.spShowAll}}&nbsp;&nbsp;<span class="asp-buttom-ammount-{{offersNumberLength}}">{{detailsToClosed.offerNumber}}</span>',
                '</div>',
              '</div>',
            '</div>',
          '{{/showShowAllButton}}',
        '</div>',
        '<div class="asp-panel-min-bottom">',
          {temp: "security"},
          {temp: "securityWithIcon"},
        '</div>',
      '</div>',
    ],
    security: [
      '<div id="asp-not-verified{{^isPanelMin}}-panel{{/isPanelMin}}">',
        '<div class="asp-hover-text">',
          '{{panelData.strings.spSiteNotVerifiedHover}}',
        '</div>',
      '</div>',
      '<div class="asp-security-left {{^isPanelMin}}{{^urlData.match}}asp-sas-display-none{{/urlData.match}}{{/isPanelMin}}">',
        '<div class="asp-security-left-safe" {{#urlData.isfakeShop}}id="fakeShop{{^isPanelMin}}Panel{{/isPanelMin}}"{{/urlData.isfakeShop}}>',
          '{{^urlData.isfakeShop}}',
            '<img ondragstart="return false;" class="asp-security-image" src="{{panelData.images.shield}}" onerror="this.src=\'{{panelData.images.shield}}\';"/>',
            '<div class="asp-security-description">{{panelData.strings.spSiteVerified}}</div>',
          '{{/urlData.isfakeShop}}',
          '{{#urlData.isfakeShop}}',
            '<img ondragstart="return false;" class="asp-security-image" src="{{panelData.images.shieldRed}}" onerror="this.src=\'{{panelData.images.shieldRed}}\';"/>',
            '<div class="asp-security-description-red">{{panelData.strings.spSiteNotVerified}}</div>',
          '{{/urlData.isfakeShop}}',
        '</div>',
      '</div>',
    ],
    securityWithIcon: [
      '<div class="asp-security-right-with-img">',
        '<img ondragstart="return false;" class="asp-security-right-image-{{#panelData.avastBranding}}avast{{/panelData.avastBranding}}{{^panelData.avastBranding}}avg{{/panelData.avastBranding}}" src="{{panelData.images.powered}}" onerror="this.src=\'{{panelData.images.powered}}\';"/>',
      '</div>',
    ],
    securityWithFeedback: [
      '<div class="asp-security-right">',
        '{{^panelData.browserType.isFirefox}}',
          '<div class="asp-feedback-text">{{panelData.strings.spFeedback}}</div>',
        '{{/panelData.browserType.isFirefox}}',
      '</div>',
    ],
    fakeShopPanel:[
      '<div class="asp-fake-shop-panel" id="asp-fake-shop-panel">',
        '<div class="asp-fake-shop-header" id="asp-fake-shop-header">',
          '<img ondragstart="return false;" class="asp-header-logo" id="asp-fake-shop-header-logo" src="{{panelData.images.logo}}" onerror="this.src=\'{{panelData.images.logo}}\';"/>',
          '{{#urlData.showFakeShop}}',
              '<div class="asp-header-close" id="asp-fake-shop-close" style="background-image: url({{panelData.images.close}});"></div>',
          '{{/urlData.showFakeShop}}',
        '</div>',
        '<div class="{{#urlData.showFakeShop}}asp-fake-shop-body{{/urlData.showFakeShop}}{{^urlData.showFakeShop}}{{#urlData.isPhishing}}asp-phishing-body{{/urlData.isPhishing}}{{/urlData.showFakeShop}}">',
          '<img ondragstart="return false;" class="asp-warning-icon" src="{{panelData.images.warningIcon}}" onerror="this.src=\'{{panelData.images.warningIcon}}\';"/>',
          '<div class="asp-warning-title">{{#urlData.showFakeShop}}{{panelData.strings.spSiteUntrustworthy}}{{/urlData.showFakeShop}}{{^urlData.showFakeShop}}{{#urlData.isPhishing}}{{panelData.strings.spPhishingSite}}{{/urlData.isPhishing}}{{/urlData.showFakeShop}}</div>',
          '<div class="asp-warning-description">{{#urlData.showFakeShop}}{{panelData.strings.spSiteUntrustworthyDesc}}{{/urlData.showFakeShop}}{{^urlData.showFakeShop}}{{#urlData.isPhishing}}{{panelData.strings.spPhishingSiteDesc}}{{/urlData.isPhishing}}{{/urlData.showFakeShop}}</div>',
          '<div class="asp-warning-button-row">',
            '<div class="asp-warning-button">',
              '<div class="asp-warning-buttom-text">{{panelData.strings.spLeaveSite}}</div>',
          '</div>',
          '</div>',
          '{{#urlData.showFakeShop}}',
            '<div class="asp-warning-link">',
              '<div class="asp-warning-link-text">{{panelData.strings.spITrustThisSite}}</div>',
            '</div>',
          '{{/urlData.showFakeShop}}',
        '</div>',
        '<div class="asp-fake-shop-bottom">',
          '<img ondragstart="return false;" class="asp-powered-image-{{#panelData.avastBranding}}avast{{/panelData.avastBranding}}{{^panelData.avastBranding}}avg{{/panelData.avastBranding}}" src="{{panelData.images.powered}}" onerror="this.src=\'{{panelData.images.powered}}\';"/>',
        '</div>',
      '</div>',
    ],
    searchOffersBox: [
      '{{#accommodationsLength}}',
        {temp: 'searchBoxAccommodations'},
      '{{/accommodationsLength}}',
      '{{^accommodationsLength}}',
        '{{#panelData.searchBack.lastOffersSearchPos}}',
          {temp: 'searchBoxOffersExpandedWithBack'}, //if collapsed will be hidden to be shown on click
        '{{/panelData.searchBack.lastOffersSearchPos}}',
        '{{^panelData.searchBack.lastOffersSearchPos}}',
          {temp: 'searchBoxOffersExpanded'}, //if collapsed will be hidden to be shown on click
        '{{/panelData.searchBack.lastOffersSearchPos}}',
        {temp: 'searchBoxOffersCollapsed'},
      '{{/accommodationsLength}}',
    ],
    searchCouponsBox: [
      '{{#panelData.searchBack.lastCouponsSearchPos}}',
        {temp: 'searchBoxCouponsExpandedWithBack'}, //if collapsed will be hidden to be shown on click
      '{{/panelData.searchBack.lastCouponsSearchPos}}',
      '{{^panelData.searchBack.lastCouponsSearchPos}}',
        {temp: 'searchBoxCouponsExpanded'}, //if collapsed will be hidden to be shown on click
      '{{/panelData.searchBack.lastCouponsSearchPos}}',
      {temp: 'searchBoxCouponsCollapsed'},
    ],
    searchBoxOffersExpanded: [
      '<div class="a-sp-search-box{{#panelData.searchConfig.offers.designType.collapsed}}{{#offerstTotalLength}} asp-sas-display-none{{/offerstTotalLength}}{{/panelData.searchConfig.offers.designType.collapsed}}">',
        '<input autocomplete="off" type="text" class="a-sp-search-input" id="query-search-offers" value="{{#panelData.strings.searchTitleOffers}}{{panelData.strings.searchTitleOffers}}{{/panelData.strings.searchTitleOffers}}" placeholder="{{panelData.strings.spProductsSearchInput}}"/>',
        '<img ondragstart="return false;" class="a-sp-search-image" id="a-sp-search-image-offers-expanded" src="{{panelData.images.searchIcon}}" onerror="this.src=\'{{panelData.images.searchIcon}}\';"/>',
        '<div class="a-sp-search-loading asp-sas-display-none" id="a-sp-search-loading-offers"></div>',
        '{{#panelData.isInstallUrl}}{{#panelData.showOffersTooltip}}',
          '<div class="asp-install-tooptip"  id="asp-install-tooptip-offers">',
            '<div class="asp-default-tooltip-text">{{panelData.strings.spOnboardingSearchOffers}}</div>',
          '</div>',
        '{{/panelData.showOffersTooltip}}{{/panelData.isInstallUrl}}',
      '</div>',
    ],
    searchBoxOffersExpandedWithBack: [
      '<div class="a-sp-search-box-with-back{{#panelData.searchConfig.offers.designType.collapsed}}{{#offerstTotalLength}} asp-sas-display-none{{/offerstTotalLength}}{{/panelData.searchConfig.offers.designType.collapsed}}">',
        '<img ondragstart="return false;" class="a-sp-search-back" id="a-sp-search-image-search-back-offers" src="{{panelData.images.back}}" onerror="this.src=\'{{panelData.images.back}}\';"/>',
        {temp: 'searchBoxOffersExpanded'},
      '</div>',
    ],
    searchBoxCouponsExpanded: [
      '<div class="a-sp-search-box{{#panelData.searchConfig.coupons.designType.collapsed}}{{#couponsLength}} asp-sas-display-none{{/couponsLength}}{{/panelData.searchConfig.coupons.designType.collapsed}}">',
        '<input autocomplete="off" type="text" class="a-sp-search-input" id="query-search-coupons" value="{{#panelData.strings.searchTitleCoupons}}{{panelData.strings.searchTitleCoupons}}{{/panelData.strings.searchTitleCoupons}}" placeholder="{{panelData.strings.spCouponsSearchInput}}"/>',
        '<img ondragstart="return false;" class="a-sp-search-image" id="a-sp-search-image-coupons-expanded" src="{{panelData.images.searchIcon}}" onerror="this.src=\'{{panelData.images.searchIcon}}\';"/>',
        '<div class="a-sp-search-loading asp-sas-display-none" id="a-sp-search-loading-coupons"></div>',
        '{{#panelData.isInstallUrl}}{{#panelData.showCouponsTooltip}}',
          '<div class="asp-install-tooptip" id="asp-install-tooptip-coupons">',
            '<div class="asp-default-tooltip-text">{{panelData.strings.spOnboardingSearchCoupons}}</div>',
          '</div>',
        '{{/panelData.showCouponsTooltip}}{{/panelData.isInstallUrl}}',
      '</div>',
    ],
    searchBoxCouponsExpandedWithBack: [
      '<div class="a-sp-search-box-with-back{{#panelData.searchConfig.coupons.designType.collapsed}}{{#couponsLength}} asp-sas-display-none{{/couponsLength}}{{/panelData.searchConfig.coupons.designType.collapsed}}">',
        '<img ondragstart="return false;" class="a-sp-search-back" id="a-sp-search-image-search-back-coupons" src="{{panelData.images.back}}" onerror="this.src=\'{{panelData.images.back}}\';"/>',
        {temp: 'searchBoxCouponsExpanded'},
      '</div>',
    ],
    searchBoxOffersCollapsed: [
      '{{#panelData.searchConfig.offers.designType.collapsed}}',
        '<div class="a-sp-search-box-collapsed{{#panelData.searchConfig.offers.designType.collapsed}}{{^offerstTotalLength}} asp-sas-display-none{{/offerstTotalLength}}{{/panelData.searchConfig.offers.designType.collapsed}}">',
          '<div class="a-sp-search-text" {{#panelData.strings.searchTitleOffers}}title="{{panelData.strings.searchTitleOffers}}"{{/panelData.strings.searchTitleOffers}}>',
            '<div class="a-sp-search-text-centered">{{#panelData.strings.searchTitleOffers}}{{panelData.strings.searchTitleOffers}}{{/panelData.strings.searchTitleOffers}}{{^panelData.strings.searchTitleOffers}}{{panelData.strings.spProductsSearchInput}}{{/panelData.strings.searchTitleOffers}}</div>',
          '</div>',
          '<img ondragstart="return false;" class="a-sp-search-image" id="a-sp-search-image-offers-collapsed" src="{{panelData.images.searchIcon}}" onerror="this.src=\'{{panelData.images.searchIcon}}\';"/>',
          '<div id="spOffersSearchIconHover">',
            '<div class="asp-hover-text">{{panelData.strings.spProductsSearchIconHover}}</div>',
          '</div>',
        '</div>',
      '{{/panelData.searchConfig.offers.designType.collapsed}}',
    ],
    searchBoxCouponsCollapsed: [
      '{{#panelData.searchConfig.coupons.designType.collapsed}}',
        '<div class="a-sp-search-box-collapsed{{#panelData.searchConfig.coupons.designType.collapsed}}{{^couponsLength}} asp-sas-display-none{{/couponsLength}}{{/panelData.searchConfig.coupons.designType.collapsed}}">',
          '<div class="a-sp-search-text" {{#panelData.strings.searchTitleCoupons}}title="{{panelData.strings.searchTitleCoupons}}"{{/panelData.strings.searchTitleCoupons}}>',
            '<div class="a-sp-search-text-centered">{{#panelData.strings.searchTitleCoupons}}{{panelData.strings.searchTitleCoupons}}{{/panelData.strings.searchTitleCoupons}}{{^panelData.strings.searchTitleCoupons}}{{panelData.strings.spCouponsSearchInput}}{{/panelData.strings.searchTitleCoupons}}</div>',
          '</div>',
          '<img ondragstart="return false;" class="a-sp-search-image" id="a-sp-search-image-coupons-collapsed" src="{{panelData.images.searchIcon}}" onerror="this.src=\'{{panelData.images.searchIcon}}\';"/>',
          '<div id="spCouponsSearchIconHover">',
            '<div class="asp-hover-text">{{panelData.strings.spCouponsSearchIconHover}}</div>',
          '</div>',
        '</div>',
      '{{/panelData.searchConfig.coupons.designType.collapsed}}',
    ],
    searchBoxAccommodations: [
      '<div class="a-sp-search-box-collapsed">',
        '<div class="a-sp-search-text">',
          '<div class="a-sp-search-text-centered" {{#panelData.strings.searchTitleOffers}}title="{{panelData.strings.searchTitleOffers}}"{{/panelData.strings.searchTitleOffers}}>{{#panelData.strings.searchTitleOffers}}{{panelData.strings.searchTitleOffers}}{{/panelData.strings.searchTitleOffers}}</div>',
        '</div>',
      '</div>',
    ],
    ratePanel: [
      '<div class="a-sp-rate-panel" id="ratePanel">',
        {temp: "rateFeedbackShare"},
        {temp: "rateFeedbackGeneral"},
        {temp: "rateFeedbackReportShop1"},
        {temp: "rateFeedbackReportShop2"},
        {temp: "rateFeedbackThanks"},
      '</div>',
    ],
    rateFeedbackShare:[
      '<div class="a-sp-rate-panel-feedback-share">',
        '<div class="a-sp-rate-top-title">{{panelData.strings.spFeedbackShare}}</div>',
        '<img ondragstart="return false;" class="a-sp-rate-top-icon" src="{{panelData.images.arrowRate}}" onerror="this.src=\'{{panelData.images.arrowRate}}\';"/>',
        '<div class="a-sp-rate-middle-container" id="share">',
          '<div class="asp-general-feedback-container">',
            '<div class="asp-feedback-white-container-left">',
              '<div class="asp-feedback-white-container-title">{{panelData.strings.spFeedbackGeneral}}</div>',
              '<div class="asp-feedback-white-container-title-desc">{{panelData.strings.spFeedbackGeneralDesc}}</div>',
              '</div>',
            '<img ondragstart="return false;" class="asp-feedback-white-container-icon" src={{panelData.images.arrowFeedback}} onerror="this.src=\'{{panelData.images.arrowFeedback}}\';"/>',
          '</div>',
          '<div class="asp-online-shop-container">',
            '<div class="asp-feedback-white-container-left">',
              '<div class="asp-feedback-white-container-title">{{panelData.strings.spFeedbackReportOnlineStore}}</div>',
              '<div class="asp-feedback-white-container-title-desc">{{panelData.strings.spFeedbackReportOnlineStoreDesc}}</div>',
              '</div>',
            '<img ondragstart="return false;" class="asp-feedback-white-container-icon" src={{panelData.images.arrowFeedback}} onerror="this.src=\'{{panelData.images.arrowFeedback}}\';"/>',
          '</div>',
        '</div>',
      '</div>',
    ],
    rateFeedbackGeneral:[
      '<div class="a-sp-rate-panel-feedback-general a-sp-rate-panel-hidden">',
        '<div class="a-sp-rate-top-title">{{panelData.strings.spFeedbackGeneral}}</div>',
        '<img ondragstart="return false;" class="a-sp-rate-top-icon" src="{{panelData.images.arrowRate}}" onerror="this.src=\'{{panelData.images.arrowRate}}\';"/>',
        '<div class="a-sp-rate-middle-container" id="general">',
          '<div class="asp-general-container-title">{{panelData.strings.spFeedbackSPExp}}</div>',
          '<div class="asp-general-wrapper-text-area">',
            '<textarea data-gramm_editor="false" data-gramm="false autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" class="asp-general-text-area" placeholder="{{panelData.strings.spFeedbackWriteAComment}}"></textarea>',
          '</div>',
        '</div>',
        '<div class="a-sp-rate-bottom">',
          '<div class="a-sp-rate-button-green a-sp-rate-button-green-disabled" id="generalSend"><div class="a-sp-rate-button-green-text">{{panelData.strings.spFeedbackSend}}</div></div>',
          '<div class="a-sp-rate-button-transparent" id="generalBack"><div class="a-sp-rate-button-transparent-text">{{panelData.strings.spFeedbackback}}</div></div>',
        '</div>',
      '</div>',
    ],
    rateFeedbackReportShop1:[
      '<div class="a-sp-rate-panel-feedback-report-shop-1 a-sp-rate-panel-hidden">',
        '<div class="a-sp-rate-top-title">{{panelData.strings.spFeedbackReportOnlineStore}}</div>',
        '<img ondragstart="return false;" class="a-sp-rate-top-icon" src="{{panelData.images.arrowRate}}" onerror="this.src=\'{{panelData.images.arrowRate}}\';"/>',
        '<div class="a-sp-rate-middle-container" id="shop1">',
          '<div class="asp-shop1-title">{{{panelData.strings.spFeedbackWhichOnlineStoreReporting}}}</div>',
          '<div class="asp-shop1-title-online-store">{{panelData.strings.spFeedbackOnlineStoreName}}</div>',
          '<div class="asp-shop1-input-box-online-store">',
            '<input autocomplete="off" type="text" class="asp-shop1-input-online-store" placeholder="{{panelData.strings.spFeedbackRetailerMerchant}}"></input>',
          '</div>',
          '<div class="asp-shop1-title-product">{{panelData.strings.spFeedbackProductOrdered}}</div>',
          '<div class="asp-shop1-input-box-product">',
            '<input autocomplete="off" type="text" class="asp-shop1-input-product" placeholder="{{panelData.strings.spFeedbackLinkToProductPage}}"></input>',
          '</div>',
        '</div>',
        '<div class="a-sp-rate-bottom">',
          '<div class="a-sp-rate-button-green a-sp-rate-button-green-disabled" id="shop1Next"><div class="a-sp-rate-button-green-text">{{panelData.strings.spFeedbackNext}}</div></div>',
          '<div class="a-sp-rate-button-transparent"  id="shop1Back"><div class="a-sp-rate-button-transparent-text">{{panelData.strings.spFeedbackback}}</div></div>',
        '</div>',
      '</div>',
    ],
    rateFeedbackReportShop2:[
      '<div class="a-sp-rate-panel-feedback-report-shop-2 a-sp-rate-panel-hidden">',
        '<div class="a-sp-rate-top-title">{{panelData.strings.spFeedbackReportOnlineStore}}</div>',
        '<img ondragstart="return false;" class="a-sp-rate-top-icon" src="{{panelData.images.arrowRate}}" onerror="this.src=\'{{panelData.images.arrowRate}}\';"/>',
        '<div class="a-sp-rate-middle-container" id="shop2">',
          '<div class="asp-shop2-top">',
            '<div class="asp-shop2-title">{{{panelData.strings.spFeedbackProblem}}}</div>',
            '<div class="asp-shop2-something-different">',
              '<input type="radio" name="aspInputShop2" class="asp-shop2-radiobutton-something-different" id="shop2SomethingDiff">',
              '<label for="shop2SomethingDiff" class="asp-shop2-label-something-different">{{panelData.strings.spFeedbackSomethingDifferent}}</label>',
            '</div>',
            '<div class="asp-shop2-paid-not-get">',
              '<input type="radio" name="aspInputShop2" class="asp-shop2-radiobutton-paid-not-get" id="shop2PaidNotGet">',
              '<label for="shop2PaidNotGet" class="asp-shop2-label-paid-not-get">{{panelData.strings.spFeedbackPaidAndNotGet}}</label>',
            '</div>',
            '<div class="asp-shop2-other">',
              '<input type="radio" name="aspInputShop2" class="asp-shop2-radiobutton-other" id="shop2Other">',
              '<label for="shop2Other" class="asp-shop2-label-other">{{panelData.strings.spFeedbackOther}}</label>',
            '</div>',
          '</div>',
          '<div class="asp-shop2-text-area-other">',
            '<textarea data-gramm_editor="false" data-gramm="false autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" class="asp-shop2-text-area asp-shop2-text-area-hidden" placeholder="{{panelData.strings.spFeedbackWhatWasTheProblem}}"></textarea>',
          '</div>',
        '</div>',
        '<div class="a-sp-rate-bottom">',
          '<div class="a-sp-rate-button-green a-sp-rate-button-green-disabled" id="shop2Send"><div class="a-sp-rate-button-green-text">{{panelData.strings.spFeedbackSend}}</div></div>',
          '<div class="a-sp-rate-button-transparent" id="shop2Back"><div class="a-sp-rate-button-transparent-text" >{{panelData.strings.spFeedbackback}}</div></div>',
        '</div>',
      '</div>',
    ],
    rateFeedbackThanks:[
      '<div class="a-sp-rate-panel-feedback-thanks a-sp-rate-panel-hidden">',
        '<img ondragstart="return false;" class="a-sp-rate-top-icon" src="{{panelData.images.arrowRate}}" onerror="this.src=\'{{panelData.images.arrowRate}}\';"/>',
        '<div class="a-sp-rate-middle-container" id="thanks">',
          '<img ondragstart="return false;" class="a-sp-rated-thanks-icon" src="{{panelData.images.checkGif}}" onerror="this.src=\'{{panelData.images.checkGif}}\';"/>',
          '<div class="a-sp-rated-thanks-title">{{panelData.strings.spFeedbackThanks}}</div>',
        '</div>',
      '</div>',
    ],

    templateDINovOffers:[
      '<div class="asp-di-container">',
        '<div class="asp-di-header">',
          '<img ondragstart="return false;" class="asp-di-header-logo" src="{{panelData.images.logo}}" onerror="this.src=\'{{panelData.images.logo}}\';"/>',
          '<div class="asp-di-header-title">{{panelData.strings.spMoreOffersFound}}</div>',
        '</div>',
        '<div class="asp-di-content" >',
          '{{#products.0}}',
            {temp:"templateDINovOffer"},
          '{{/products.0}}',
          '{{#products.1}}',
            {temp:"templateDINovOffer"},
          '{{/products.1}}',
          '<div class="asp-di-content-arrow" style="background-image: url({{panelData.images.arrowDi}});">',
          '</div>',
        '</div>',
      '</div>',
    ],
    templateDINovOffer:[
      '<div class="asp-di-content-offer" resurl="{{url}}">',
        '{{#productImage}}',
          '<img ondragstart="return false;" class="asp-di-offer-img" src="{{productImage}}" onerror="this.src=\'{{panelData.images.searchOffers}}\';"/>',
        '{{/productImage}}',
        '{{^productImage}}',
          '<img ondragstart="return false;" class="asp-di-offer-img" src="{{image}}" onerror="this.src=\'{{panelData.images.searchOffers}}\';"/>',
        '{{/productImage}}',
        '<div class="asp-di-offer-title">{{title}}</div>',
        '<div class="asp-di-offer-domain">{{affiliate}}</div>',
        '<div class="asp-di-offer-price">{{formattedPrice}}</div>',
      '</div>',
      '<div class="asp-di-content-offer-hover" >',
        '<div class="asp-di-offer-hover-description" >{{title}}</div>',
      '</div>',
    ],
    templateOptIn:[
      '<div class="opt-in-body-new">',
        '<div class="asp-opt-in-body"></div>',
        '<div class="asp-opt-in-container">',
          '<div class="opt-in-box">',
            '<div class="opt-in-box-header">',
                '<img class= "asp-logo" src="{{logo}}" alt="" class="src">',
                '<img  class= "asp-img-1" src="{{piggy}}" alt="" class="src">',
                '<img  class= "asp-img-2 hide" src="{{mark}}" alt="" class="src">',
            '</div>',
            '<div class="opt-in-box-content" id="opt-in-content-1">',
              '<div class="opt-in-box-notice">',
                '<div class="opt-in-box-notice-text">{{{spOptInTitleB}}}</div>',
                '<div class="opt-in-box-notice-policy">',
                  '{{spOptInPoliceB}}',
                  '<div class="opt-in-list">',
                    '<div class="opt-in-list-item">{{spOptInPolice1}}</div>',
                    '<div class="opt-in-list-item">{{spOptInPolice2}}</div>',
                    '<div class="opt-in-list-item">{{spOptInPolice3}}</div>',
                  '</div>',
                  '<div class="opt-in-link">{{{spOptInPoliceLink}}}</div>',
                '</div>',
              '</div>',
              '<div class="opt-in-box-buttons">',
                '<div class="opt-in-box-buttons-corner-1"></div>',
                '<div class="opt-in-box-buttons-decline" id="opt-in-decline">',
                  '<img  class= "opt-in-buttons-img-cross" src="{{cross}}" alt="" class="src">',
                  '<div class="opt-in-buttons-text">{{spOptInPoliceDeny}}</div>',
                '</div>',
                '<div class="opt-in-box-buttons-mittle"></div>',
                '<div class="opt-in-box-buttons-accept" id="opt-in-accept">',
                  '<img  class= "opt-in-buttons-img-check" src="{{check}}" alt="" class="src">',
                  '<div class="opt-in-buttons-text">{{spOptInPoliceAcceptB}}</div>',
                '</div>',
                '<div class="opt-in-box-buttons-corner-2"></div>',
              '</div>',
            '</div>',
            '<div class="opt-in-box-content hide" id="opt-in-content-2">',
              '<div class="opt-in-box-notice">',
                '<div class="opt-in-box-notice-text">{{spOptInSecondTitleB}} </div>',
                '<div class="opt-in-box-notice-policy">{{spOptInSecondText}}</div>' ,
              '</div>',
              '<div class="opt-in-box-buttons">',
                '<div class="opt-in-box-buttons-corner-1"></div>',
                '<div class="opt-in-box-buttons-decline" id="opt-in-close">',
                  '<img  class= "opt-in-buttons-img-cross" src="{{cross}}" alt="" class="src">',
                  '<div class="opt-in-buttons-text">{{spOptInSecondClose}}</div>',
                '</div>',
                '<div class="opt-in-box-buttons-mittle"></div>',
                '<div class="opt-in-box-buttons-accept" id="opt-in-revisit">',
                  '<img  class= "opt-in-buttons-img-check" src="{{check}}" alt="" class="src">',
                  '<div class="opt-in-buttons-text">{{spOptInSecondReviewConsent}}</div>',
                '</div>',                  
                '<div class="opt-in-box-buttons-corner-2"></div>',
              '</div>',
            '</div>',
          '</div>',
        '</div>',
      '</div>',
    ]
    // --ende templates declarations --
  });
