#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2023 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg@outlook.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30
#=============================================================================
# My Custom Plugins
#=============================================================================

[[custom_plugins]]
    repo = "https://github.com/vim-airline/vim-airline"
    merged = 0

[[custom_plugins]]
    repo = "https://github.com/vim-airline/vim-airline-themes"
    merged = 0

[[custom_plugins]]
    repo = "https://github.com/frazrepo/vim-rainbow"
    merged = 0

[[custom_plugins]]
    repo = "https://github.com/evturn/cosmic-barf"
    merged = 0

[[custom_plugins]]
    repo = "https://github.com/liuchengxu/space-vim-dark"
    merged = 0

[[custom_plugins]]
    repo = "https://github.com/dbeniamine/cheat.sh-vim"
    merged = 0

[[auto_completion_return_key_behaviorstom_plugins]]
    repo = "https://github.com/justinmk/vim-sneak"
    merged = 0

[[custom_plugins]]
    repo = "https://github.com/tpope/vim-fugitive"
    merged = 0

[[custom_plugins]]
  repo = "https://github.com/vifm/vifm.vim"
  merged = 0

[[custom_plugins]]
  repo = "https://github.com/airblade/vim-gitgutter"
  merged = 0

[[custom_plugins]]
  repo = "https://github.com/ojroques/vim-scrollstatus"
  merged = 0

[[custom_plugins]]
  repo = "https://github.com/pR0Ps/molokai-dark"
  merged = 0

[[custom_plugins]]
  repo = "https://github.com/airblade/vim-rooter"
  merged = 0

[[custom_plugins]]
  repo = "https://github.com/junegunn/fzf.vim"
  merged = 0

[[custom_plugins]]
  repo = "https://github.com/junegunn/fzf"
  merged = 0

[[custom_plugins]]
  repo = "https://github.com/Brettm12345/moonlight.vim"
  merged = 0

[[custom_plugins]]
  repo = "https://github.com/coreyja/fzf.devicon.vim"
  merged = 0

[[custom_plugins]]
  repo = "https://github.com/ryanoasis/vim-devicons"
  merged = 0

[[custom_plugins]]
  repo = "https://github.com/dracula/vim"
  merged = 0

[[custom_plugins]]
  repo = "https://github.com/francoiscabrol/ranger.vim"
  merged = 0

[[custom_plugins]]
  repo = "https://github.com/vim-pandoc/vim-pandoc.git"
  merged = 0

[[custom_plugins]]
  repo = "https://github.com/vim-pandoc/vim-pandoc-syntax.git"
  merged = 0

[[custom_plugins]]
  repo = "https://github.com/vimwiki/vimwiki.git"
  merged = 0
